version: "3"

services:
  stat_server:
    image: idoge/stat_server:1.6.2
    container_name: stat_server
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.toml:/config.toml
      - ./stats.json:/stats.json
    ports:
      - 10006:8080
      - 10106:9394

